import "./globals.css";
import Navbar from "./components/navbar/navbar-desktop/navbar-desktop";
import Background from "./components/background/background-animation";
// import { Inter } from "next/font/google"

// const inter = Inter({ subsets: ["latin"] })

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <Background />
        <Navbar /> */}
        {children}
      </body>
    </html>
  )
}
